<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Dapper.Oracle" Version="2.0.2" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.300" />
		<PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.8" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DynamicTransaction\DynamicTransaction.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="ConnectionDll">
			<HintPath>Infrastructure\Data\ExternalSources\ConnectionDll.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Controllers\" />
	  <Folder Include="Models\" />
	</ItemGroup>
</Project>
