-- Create RBAC Schema for MySQL

DROP TABLE IF EXISTS JAN_USER_SESSIONS;
DROP TABLE IF EXISTS JAN_AUDIT_LOG;
DROP TABLE IF EXISTS JAN_USER_ACCESS_RIGHTS;
DROP TABLE IF EXISTS JAN_ROLE_MENU;
DROP TABLE IF EXISTS JAN_USER_MASTER;
DROP TABLE IF EXISTS JAN_MENUS;
DROP TABLE IF EXISTS JAN_MODULES;
DROP TABLE IF EXISTS JAN_ROLES;
DROP TABLE IF EXISTS JAN_QUERY_DEFINITION_DEV;

-- 1. JAN_ROLES
CREATE TABLE JAN_ROLES (
    ROLE_ID        INT AUTO_INCREMENT PRIMARY KEY,
    ROLE_CODE      VARCHAR(10)   NOT NULL,
    ROLE_NAME      VARCHAR(100)  NOT NULL,
    SOURCE_TYPE    VARCHAR(20)   NOT NULL,
    REMARKS        VARCHAR(400),
    ROLE_VERSION   VARCHAR(10),
    STATUS         VARCHAR(10)   NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY     VARCHAR(50)   NOT NULL,
    CREATED_DATE   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY    VARCHAR(50),
    MODIFIED_DATE  DATETIME,
    CONSTRAINT UQ_JAN_ROLES_CODE UNIQUE (ROLE_CODE),
    CONSTRAINT CK_JAN_ROLES_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE'))
) ENGINE=InnoDB;

-- 2. JAN_MODULES
CREATE TABLE JAN_MODULES (
    MODULE_ID      INT AUTO_INCREMENT PRIMARY KEY,
    MODULE_CODE    VARCHAR(10)   NOT NULL,
    MODULE_NAME    VARCHAR(100)  NOT NULL,
    DEFAULT_MENU   VARCHAR(100),
    SORT_ORDER     SMALLINT,
    REMARKS        VARCHAR(400),
    STATUS         VARCHAR(10)   NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY     VARCHAR(50)   NOT NULL,
    CREATED_DATE   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY    VARCHAR(50),
    MODIFIED_DATE  DATETIME,
    CONSTRAINT UQ_JAN_MODULES_CODE UNIQUE (MODULE_CODE),
    CONSTRAINT CK_JAN_MODULES_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE'))
) ENGINE=InnoDB;

-- 3. JAN_MENUS
CREATE TABLE JAN_MENUS (
    MENU_ID         INT AUTO_INCREMENT PRIMARY KEY,
    MENU_CODE       VARCHAR(10)   NOT NULL,
    MENU_NAME       VARCHAR(100)  NOT NULL,
    DISPLAY_NAME    VARCHAR(100)  NOT NULL,
    MODULE_ID       INT           NOT NULL,
    PARENT_MENU_ID  INT,
    MENU_TYPE       VARCHAR(20)   NOT NULL,
    NATURE          VARCHAR(20)   NOT NULL,
    SORT_ORDER      SMALLINT,
    STATUS          VARCHAR(10)   NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY      VARCHAR(50)   NOT NULL,
    CREATED_DATE    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY     VARCHAR(50),
    MODIFIED_DATE   DATETIME,
    MENU_PATH       VARCHAR(100),
    MENU_ICON       VARCHAR(100),
    CONSTRAINT UQ_JAN_MENUS_CODE UNIQUE (MENU_CODE),
    CONSTRAINT CK_JAN_MENUS_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE')),
    CONSTRAINT CK_JAN_MENUS_TYPE CHECK (MENU_TYPE IN ('MASTER','TRANSACTION','REPORT')),
    CONSTRAINT FK_JAN_MENUS_MODULE FOREIGN KEY (MODULE_ID) REFERENCES JAN_MODULES(MODULE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_JAN_MENUS_PARENT FOREIGN KEY (PARENT_MENU_ID) REFERENCES JAN_MENUS(MENU_ID) ON DELETE SET NULL
) ENGINE=InnoDB;

-- 4. JAN_USER_MASTER
CREATE TABLE JAN_USER_MASTER (
    USER_ID              INT AUTO_INCREMENT PRIMARY KEY,
    USER_CODE            VARCHAR(10)   NOT NULL,
    EMPLOYEE_ID          VARCHAR(50)   NOT NULL,
    FULL_NAME            VARCHAR(150)  NOT NULL,
    USER_NAME            VARCHAR(50)   NOT NULL,
    PASSWORD_HASH        VARCHAR(256)  NOT NULL,
    PASSWORD_SALT        VARCHAR(256)  NOT NULL,
    USER_TYPE            VARCHAR(20)   NOT NULL,
    SECURITY_LEVEL       SMALLINT      NOT NULL,
    ROLE_ID              INT           NOT NULL,
    REPORTING_TO         INT,
    VALID_FROM           DATE          NOT NULL,
    VALID_TO             DATE,
    STATUS               VARCHAR(10)   NOT NULL DEFAULT 'ACTIVE',
    PRIMARY_EMAIL         VARCHAR(150),
    PRIMARY_MOBILE        VARCHAR(20),
    PASSWORD_POLICY       VARCHAR(20),
    WORK_OPERATING_UNIT   INT,
    THEME                 VARCHAR(30),
    TIMEZONE              VARCHAR(50),
    MAX_SESSIONS          SMALLINT,
    LOGIN_WORKDAYS_ONLY   CHAR(1),
    LOGIN_FROM_TIME       VARCHAR(5),
    LOGIN_TO_TIME         VARCHAR(5),
    ALLOWED_MACHINES      VARCHAR(500),
    ALLOWED_IPS           VARCHAR(500),
    DIGITAL_SIG_FILE      VARCHAR(300),
    DIGITAL_SIG_PWD_ENC   VARCHAR(300),
    CREATED_BY           VARCHAR(50)   NOT NULL,
    CREATED_DATE         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY           VARCHAR(50),
    MODIFIED_DATE          DATETIME,
    CONSTRAINT UQ_JAN_USER_CODE UNIQUE (USER_CODE),
    CONSTRAINT UQ_JAN_USER_NAME UNIQUE (USER_NAME),
    CONSTRAINT CK_JAN_USER_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE','LOCKED')),
    CONSTRAINT FK_JAN_USER_ROLE FOREIGN KEY (ROLE_ID) REFERENCES JAN_ROLES(ROLE_ID) ON DELETE RESTRICT,
    CONSTRAINT FK_JAN_USER_REPORTING FOREIGN KEY (REPORTING_TO) REFERENCES JAN_USER_MASTER(USER_ID) ON DELETE SET NULL
) ENGINE=InnoDB;

-- 5. JAN_ROLE_MENU
CREATE TABLE JAN_ROLE_MENU (
    ROLE_MENU_ID       INT AUTO_INCREMENT PRIMARY KEY,
    ROLE_ID            INT           NOT NULL,
    MODULE_ID          INT           NOT NULL,
    MENU_ID            INT           NOT NULL,
    PERM_VIEW          CHAR(1)       NOT NULL DEFAULT 'N',
    PERM_ADD           CHAR(1)       NOT NULL DEFAULT 'N',
    PERM_EDIT          CHAR(1)       NOT NULL DEFAULT 'N',
    PERM_DELETE        CHAR(1)       NOT NULL DEFAULT 'N',
    PERM_EXPORT        CHAR(1)       NOT NULL DEFAULT 'N',
    PERM_APPROVE       CHAR(1)       NOT NULL DEFAULT 'N',
    RESTRICTED_COLUMNS VARCHAR(1000),
    CREATED_BY         VARCHAR(50)   NOT NULL,
    CREATED_DATE       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY        VARCHAR(50),
    MODIFIED_DATE      DATETIME,
    CONSTRAINT UQ_JAN_ROLE_MENU UNIQUE (ROLE_ID, MENU_ID),
    CONSTRAINT CK_JAN_ROLE_MENU_VIEW    CHECK (PERM_VIEW    IN ('Y','N')),
    CONSTRAINT CK_JAN_ROLE_MENU_ADD     CHECK (PERM_ADD     IN ('Y','N')),
    CONSTRAINT CK_JAN_ROLE_MENU_EDIT    CHECK (PERM_EDIT    IN ('Y','N')),
    CONSTRAINT CK_JAN_ROLE_MENU_DELETE  CHECK (PERM_DELETE  IN ('Y','N')),
    CONSTRAINT CK_JAN_ROLE_MENU_EXPORT  CHECK (PERM_EXPORT  IN ('Y','N')),
    CONSTRAINT CK_JAN_ROLE_MENU_APPROVE CHECK (PERM_APPROVE IN ('Y','N')),
    CONSTRAINT FK_JAN_ROLE_MENU_ROLE   FOREIGN KEY (ROLE_ID)   REFERENCES JAN_ROLES(ROLE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_JAN_ROLE_MENU_MODULE FOREIGN KEY (MODULE_ID) REFERENCES JAN_MODULES(MODULE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_JAN_ROLE_MENU_MENU   FOREIGN KEY (MENU_ID)   REFERENCES JAN_MENUS(MENU_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 6. JAN_USER_ACCESS_RIGHTS
CREATE TABLE JAN_USER_ACCESS_RIGHTS (
    UAR_ID          INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID         INT           NOT NULL,
    OPERATING_UNIT  INT           NOT NULL,
    ORGANIZATION_ID INT           NOT NULL,
    LIMIT_VALUE     DECIMAL(15,2),
    ACCESS_CHANNEL  VARCHAR(10)   NOT NULL,
    STATUS          VARCHAR(10)   NOT NULL DEFAULT 'ACTIVE',
    REMARKS         VARCHAR(400),
    CREATED_BY      VARCHAR(50)   NOT NULL,
    CREATED_DATE    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY     VARCHAR(50),
    MODIFIED_DATE   DATETIME,
    CONSTRAINT CK_JAN_UAR_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE')),
    CONSTRAINT CK_JAN_UAR_CHANNEL CHECK (ACCESS_CHANNEL IN ('WEB','MOBILE','API','ALL', 'SYSTEM', 'BOTH')),
    CONSTRAINT FK_JAN_UAR_USER FOREIGN KEY (USER_ID) REFERENCES JAN_USER_MASTER(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 7. JAN_AUDIT_LOG
CREATE TABLE JAN_AUDIT_LOG (
    AUDIT_ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    TABLE_NAME   VARCHAR(60)  NOT NULL,
    RECORD_PK    VARCHAR(60)  NOT NULL,
    ACTION_TYPE  VARCHAR(10)  NOT NULL,
    OLD_VALUE    LONGTEXT,
    NEW_VALUE    LONGTEXT,
    ACTION_BY    VARCHAR(50)  NOT NULL,
    ACTION_DATE  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_JAN_AUDIT_ACTION CHECK (ACTION_TYPE IN ('INSERT','UPDATE','DELETE')),
    INDEX IX_JAN_AUDIT_TABLE_PK (TABLE_NAME, RECORD_PK)
) ENGINE=InnoDB;

-- 8. JAN_USER_SESSIONS
CREATE TABLE JAN_USER_SESSIONS (
    SESSION_ID    INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID       INT           NOT NULL,
    SESSION_TOKEN VARCHAR(250)  NOT NULL,
    IP_ADDRESS    VARCHAR(50),
    MACHINE_NAME  VARCHAR(200),
    STATUS        VARCHAR(10)   NOT NULL DEFAULT 'ACTIVE',
    CREATED_DATE  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_ACTIVITY DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXPIRES_AT    DATETIME      NOT NULL,
    ENDED_DATE    DATETIME,
    CONSTRAINT UQ_JAN_SESSION_TOKEN UNIQUE (SESSION_TOKEN),
    CONSTRAINT CK_JAN_SESSION_STATUS CHECK (STATUS IN ('ACTIVE','EXPIRED','LOGGED_OUT')),
    CONSTRAINT FK_JAN_SESSION_USER FOREIGN KEY (USER_ID) REFERENCES JAN_USER_MASTER(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 9. JAN_QUERY_DEFINITION_DEV
CREATE TABLE JAN_QUERY_DEFINITION_DEV (
    QUERY_NUMBER INT PRIMARY KEY,
    DESCRIPTION  VARCHAR(255) NOT NULL,
    QUERY_TEXT   LONGTEXT NOT NULL
) ENGINE=InnoDB;

-- ==========================================
-- Insert Query Definitions (101-121)
-- ==========================================

INSERT INTO JAN_QUERY_DEFINITION_DEV (QUERY_NUMBER, DESCRIPTION, QUERY_TEXT) VALUES
(101, 'List Modules', 'SELECT MODULE_ID, MODULE_CODE, MODULE_NAME, DEFAULT_MENU, SORT_ORDER, STATUS, REMARKS FROM JAN_MODULES ORDER BY SORT_ORDER'),
(102, 'Get Module by ID', 'SELECT MODULE_ID, MODULE_CODE, MODULE_NAME, DEFAULT_MENU, SORT_ORDER, STATUS, REMARKS FROM JAN_MODULES WHERE MODULE_ID = @ModuleId'),
(103, 'List Roles', 'SELECT ROLE_ID, ROLE_CODE, ROLE_NAME, SOURCE_TYPE, STATUS, REMARKS FROM JAN_ROLES ORDER BY ROLE_NAME'),
(104, 'Get Role by ID', 'SELECT ROLE_ID, ROLE_CODE, ROLE_NAME, SOURCE_TYPE, STATUS, REMARKS FROM JAN_ROLES WHERE ROLE_ID = @RoleId'),
(105, 'List Menus', 'SELECT m.MENU_ID, m.MENU_CODE, m.MENU_NAME, m.DISPLAY_NAME, m.MODULE_ID, md.MODULE_NAME, m.PARENT_MENU_ID, m.MENU_TYPE, m.NATURE, m.SORT_ORDER, m.STATUS, m.MENU_PATH, m.MENU_ICON FROM JAN_MENUS m LEFT JOIN JAN_MODULES md ON m.MODULE_ID = md.MODULE_ID ORDER BY m.SORT_ORDER'),
(106, 'Get Menu by ID', 'SELECT MENU_ID, MENU_CODE, MENU_NAME, DISPLAY_NAME, MODULE_ID, PARENT_MENU_ID, MENU_TYPE, NATURE, SORT_ORDER, STATUS, MENU_PATH, MENU_ICON FROM JAN_MENUS WHERE MENU_ID = @MenuId'),
(107, 'List Users', 'SELECT u.USER_ID, u.USER_CODE, u.EMPLOYEE_ID, u.FULL_NAME, u.USER_NAME, u.USER_TYPE, u.SECURITY_LEVEL, u.ROLE_ID, r.ROLE_NAME, u.VALID_FROM, u.VALID_TO, u.STATUS, u.PRIMARY_EMAIL, u.PRIMARY_MOBILE FROM JAN_USER_MASTER u LEFT JOIN JAN_ROLES r ON u.ROLE_ID = r.ROLE_ID ORDER BY u.USER_ID'),
(108, 'Get User by ID', 'SELECT USER_ID, USER_CODE, EMPLOYEE_ID, FULL_NAME, USER_NAME, USER_TYPE, SECURITY_LEVEL, ROLE_ID, VALID_FROM, VALID_TO, STATUS, PRIMARY_EMAIL, PRIMARY_MOBILE, WORK_OPERATING_UNIT, THEME, TIMEZONE, MAX_SESSIONS, LOGIN_WORKDAYS_ONLY, LOGIN_FROM_TIME, LOGIN_TO_TIME, ALLOWED_MACHINES, ALLOWED_IPS, REPORTING_TO FROM JAN_USER_MASTER WHERE USER_ID = @UserId'),
(109, 'List Role Menu Mappings', 'SELECT rm.ROLE_MENU_ID, rm.ROLE_ID, r.ROLE_NAME, rm.MODULE_ID, md.MODULE_NAME, rm.MENU_ID, m.MENU_NAME, rm.PERM_VIEW, rm.PERM_ADD, rm.PERM_EDIT, rm.PERM_DELETE, rm.PERM_EXPORT, rm.PERM_APPROVE, rm.RESTRICTED_COLUMNS FROM JAN_ROLE_MENU rm JOIN JAN_ROLES r ON rm.ROLE_ID = r.ROLE_ID JOIN JAN_MODULES md ON rm.MODULE_ID = md.MODULE_ID JOIN JAN_MENUS m ON rm.MENU_ID = m.MENU_ID'),
(110, 'Get Role Menu Mapping by ID', 'SELECT ROLE_MENU_ID, ROLE_ID, MODULE_ID, MENU_ID, PERM_VIEW, PERM_ADD, PERM_EDIT, PERM_DELETE, PERM_EXPORT, PERM_APPROVE, RESTRICTED_COLUMNS FROM JAN_ROLE_MENU WHERE ROLE_MENU_ID = @RoleMenuId'),
(111, 'List User Access Rights', 'SELECT uar.UAR_ID, uar.USER_ID, u.FULL_NAME as userName, uar.OPERATING_UNIT, uar.ORGANIZATION_ID, uar.LIMIT_VALUE, uar.ACCESS_CHANNEL, uar.STATUS, uar.REMARKS FROM JAN_USER_ACCESS_RIGHTS uar JOIN JAN_USER_MASTER u ON uar.USER_ID = u.USER_ID'),
(112, 'Get User Access Right by ID', 'SELECT UAR_ID, USER_ID, OPERATING_UNIT, ORGANIZATION_ID, LIMIT_VALUE, ACCESS_CHANNEL, STATUS, REMARKS FROM JAN_USER_ACCESS_RIGHTS WHERE UAR_ID = @UarId'),
(113, 'List Role Menu Mappings by Role ID', 'SELECT rm.ROLE_MENU_ID, rm.ROLE_ID, rm.MODULE_ID, rm.MENU_ID, rm.PERM_VIEW, rm.PERM_ADD, rm.PERM_EDIT, rm.PERM_DELETE, rm.PERM_EXPORT, rm.PERM_APPROVE, rm.RESTRICTED_COLUMNS, m.MENU_NAME, m.DISPLAY_NAME FROM JAN_ROLE_MENU rm JOIN JAN_MENUS m ON rm.MENU_ID = m.MENU_ID WHERE rm.ROLE_ID = @RoleId'),
(114, 'List Module Access', 'SELECT DISTINCT r.ROLE_ID, r.ROLE_NAME, m.MODULE_ID, m.MODULE_NAME, CASE WHEN rm.ROLE_MENU_ID IS NOT NULL THEN \'ALLOWED\' ELSE \'DENIED\' END AS ACCESS_FLAG FROM JAN_ROLES r CROSS JOIN JAN_MODULES m LEFT JOIN JAN_ROLE_MENU rm ON r.ROLE_ID = rm.ROLE_ID AND m.MODULE_ID = rm.MODULE_ID'),
(115, 'List Module Access by Role ID', 'SELECT DISTINCT r.ROLE_ID, r.ROLE_NAME, m.MODULE_ID, m.MODULE_NAME, CASE WHEN rm.ROLE_MENU_ID IS NOT NULL THEN \'ALLOWED\' ELSE \'DENIED\' END AS ACCESS_FLAG FROM JAN_ROLES r CROSS JOIN JAN_MODULES m LEFT JOIN JAN_ROLE_MENU rm ON r.ROLE_ID = rm.ROLE_ID AND m.MODULE_ID = rm.MODULE_ID WHERE r.ROLE_ID = @RoleId'),
(116, 'Get Restricted Columns by Menu ID', 'SELECT RESTRICTED_COLUMNS FROM JAN_ROLE_MENU WHERE MENU_ID = @MenuId'),
(117, 'Get User Access Rights by User ID', 'SELECT UAR_ID, USER_ID, OPERATING_UNIT, ORGANIZATION_ID, LIMIT_VALUE, ACCESS_CHANNEL, STATUS, REMARKS FROM JAN_USER_ACCESS_RIGHTS WHERE USER_ID = @UserId AND STATUS = \'ACTIVE\''),
(118, 'Verify Employee ID', 'SELECT 1 AS found, FULL_NAME AS employeeName FROM JAN_USER_MASTER WHERE EMPLOYEE_ID = @EmployeeId LIMIT 1'),
(119, 'List Menus by Module ID', 'SELECT MENU_ID, MENU_CODE, MENU_NAME, DISPLAY_NAME, MODULE_ID, PARENT_MENU_ID, MENU_TYPE, NATURE, SORT_ORDER, STATUS, MENU_PATH, MENU_ICON FROM JAN_MENUS WHERE MODULE_ID = @ModuleId AND STATUS = \'ACTIVE\' ORDER BY SORT_ORDER'),
(120, 'List Operating Units', 'SELECT 101 AS operatingUnit, \'Operating Unit 1\' AS operatingUnitName UNION SELECT 102, \'Operating Unit 2\''),
(121, 'List Organizations', 'SELECT 1 AS organizationId, \'ORG001\' AS organizationCode WHERE @OperatingUnit = 101 UNION SELECT 2, \'ORG002\' WHERE @OperatingUnit = 101 UNION SELECT 3, \'ORG003\' WHERE @OperatingUnit = 102 UNION SELECT 4, \'ORG004\' WHERE @OperatingUnit = 102'),
(122, 'PES Active Alerts', 'SELECT ALERT_ID, ALERT_TRX_ID, ALERT_CODE, CONFIG_SEVERITY, CONFIG_CLASSIFICATION, ALERT_DESCRIPTION, ALERT_SUBJECT, ALERT_TRIGGERED_TIME, ASSIGNED_TO, ALTER_REF_PAGE_NAME, ALTER_REF_ROUTE_PATH, STATUS, REMARKS FROM JAN_ALERT_TRX WHERE STATUS = \'ACTIVE\''),
(123, 'Customer Complaint Summary (WTD)', 'WITH periods AS ( SELECT DATE(@fromDate) AS cur_start, DATE(@toDate) AS cur_end, DATE_SUB(DATE(@fromDate), INTERVAL 7 DAY) AS prev_start, DATE_SUB(DATE(@toDate), INTERVAL 7 DAY) AS prev_end ), base AS ( SELECT c.CCRDT, c.CLOSE_DT, c.TARGET_COMP_DT, c.ITEM_NO, c.WEEK_SALE_QTY, CASE WHEN DATE(c.CCRDT) >= p.cur_start AND DATE(c.CCRDT) <= p.cur_end THEN \'CUR\' WHEN DATE(c.CCRDT) >= p.prev_start AND DATE(c.CCRDT) <= p.prev_end THEN \'PREV\' END AS PERIOD FROM JAN_SERVICE_CCR_zoho c CROSS JOIN periods p WHERE c.ORG_ID = @orgId ), item_orders AS ( SELECT b.PERIOD, SUM(io.QTY) AS TOTAL_DELIVERED FROM (SELECT DISTINCT PERIOD, ITEM_NO FROM base WHERE PERIOD IS NOT NULL) b JOIN ( SELECT ITEM_NO, MAX(WEEK_SALE_QTY) AS QTY FROM JAN_SERVICE_CCR_zoho WHERE ORG_ID = @orgId GROUP BY ITEM_NO ) io ON b.ITEM_NO = io.ITEM_NO GROUP BY b.PERIOD ) SELECT b.PERIOD, COUNT(*) AS TOTAL_COMPLAINTS, SUM(CASE WHEN b.CLOSE_DT IS NOT NULL AND DATE(b.CLOSE_DT) <= b.TARGET_COMP_DT THEN 1 ELSE 0 END) AS SOLVED_WITHIN_SLA, SUM(CASE WHEN b.CLOSE_DT IS NULL AND (b.TARGET_COMP_DT IS NULL OR b.TARGET_COMP_DT >= CURDATE()) THEN 1 ELSE 0 END) AS OPEN_WITHIN_SLA, SUM(CASE WHEN b.CLOSE_DT IS NULL AND b.TARGET_COMP_DT < CURDATE() THEN 1 ELSE 0 END) AS OPEN_BREACHED_SLA, COALESCE(io.TOTAL_DELIVERED, 0) AS ORDERS_DELIVERED FROM base b LEFT JOIN item_orders io ON b.PERIOD = io.PERIOD WHERE b.PERIOD IS NOT NULL GROUP BY b.PERIOD, io.TOTAL_DELIVERED'),
(124, 'Customer Complaint Trend', 'WITH trend_data AS ( SELECT DATE(CCRDT) AS DAY, SUM(CASE WHEN CLOSE_DT IS NOT NULL AND DATE(CLOSE_DT) <= TARGET_COMP_DT THEN 1 ELSE 0 END) AS SOLVED_WITHIN_SLA, SUM(CASE WHEN CLOSE_DT IS NULL AND (TARGET_COMP_DT IS NULL OR TARGET_COMP_DT >= CURDATE()) THEN 1 ELSE 0 END) AS OPEN_WITHIN_SLA, SUM(CASE WHEN CLOSE_DT IS NULL AND TARGET_COMP_DT < CURDATE() THEN 1 ELSE 0 END) AS OPEN_BREACHED_SLA, COUNT(*) AS TOTAL_COMPLAINTS FROM JAN_SERVICE_CCR_zoho WHERE ORG_ID = @orgId AND DATE(CCRDT) >= DATE(@fromDate) AND DATE(CCRDT) <= DATE(@toDate) GROUP BY DATE(CCRDT) ), orders_delivered AS ( SELECT COALESCE(SUM(QTY), 0) AS TOTAL_ORDERS FROM ( SELECT DISTINCT ITEM_NO, WEEK_SALE_QTY AS QTY FROM JAN_SERVICE_CCR_zoho WHERE ORG_ID = @orgId AND DATE(CCRDT) >= DATE(@fromDate) AND DATE(CCRDT) <= DATE(@toDate) ) t ) SELECT t.DAY, t.SOLVED_WITHIN_SLA, t.OPEN_WITHIN_SLA, t.OPEN_BREACHED_SLA, t.TOTAL_COMPLAINTS, o.TOTAL_ORDERS AS WEEK_ORDERS, ROUND(IF(o.TOTAL_ORDERS > 0, t.TOTAL_COMPLAINTS * 100.0 / o.TOTAL_ORDERS, 0), 2) AS COMPLAINT_RATE_PCT FROM trend_data t CROSS JOIN orders_delivered o ORDER BY t.DAY'),
(125, 'Product Complaint Summary (WTD) Paginated', 'WITH item_orders AS ( SELECT ITEM_NO, MAX(WEEK_SALE_QTY) AS ORDERS_DELIVERED FROM JAN_SERVICE_CCR_zoho WHERE ORG_ID = @orgId AND DATE(CCRDT) >= DATE(@fromDate) AND DATE(CCRDT) <= DATE(@toDate) GROUP BY ITEM_NO ), per_item AS ( SELECT c.ITEM_NO, MAX(c.COMP_CUS_NAME) AS COMP_CUS_NAME, MAX(c.DESCRIPTION) AS PRODUCT_DESCRIPTION, MAX(c.CUSREGION) AS CUSREGION, COUNT(*) AS TOTAL_COMPLAINTS, SUM(CASE WHEN c.CLOSE_DT IS NOT NULL AND c.CLOSE_DT <= c.TARGET_COMP_DT THEN 1 ELSE 0 END) AS SOLVED_WITHIN_SLA, SUM(CASE WHEN c.CLOSE_DT IS NULL AND (c.TARGET_COMP_DT IS NULL OR c.TARGET_COMP_DT >= CURDATE()) THEN 1 ELSE 0 END) AS OPEN_WITHIN_SLA, SUM(CASE WHEN c.CLOSE_DT IS NULL AND c.TARGET_COMP_DT < CURDATE() THEN 1 ELSE 0 END) AS OPEN_BREACHED_SLA FROM JAN_SERVICE_CCR_zoho c WHERE c.ORG_ID = @orgId AND DATE(c.CCRDT) >= DATE(@fromDate) AND DATE(c.CCRDT) <= DATE(@toDate) GROUP BY c.ITEM_NO ), final_result AS ( SELECT p.ITEM_NO, p.COMP_CUS_NAME, p.CUSREGION, p.PRODUCT_DESCRIPTION, COALESCE(io.ORDERS_DELIVERED, 0) AS ORDERS_DELIVERED, p.TOTAL_COMPLAINTS, p.SOLVED_WITHIN_SLA, p.OPEN_WITHIN_SLA, p.OPEN_BREACHED_SLA FROM per_item p LEFT JOIN item_orders io ON io.ITEM_NO = p.ITEM_NO ) SELECT f.*, COUNT(*) OVER() AS TOTAL_ROWS FROM final_result f ORDER BY f.TOTAL_COMPLAINTS DESC LIMIT @limit OFFSET @offset'),
(126, 'Product Complaint Summary Totals', 'SELECT COALESCE(SUM(io.ORDERS_DELIVERED), 0) AS ORDERS_DELIVERED, COALESCE(SUM(p.TOTAL_COMPLAINTS), 0) AS TOTAL_COMPLAINTS, COALESCE(SUM(p.SOLVED_WITHIN_SLA), 0) AS SOLVED_WITHIN_SLA, COALESCE(SUM(p.OPEN_WITHIN_SLA), 0) AS OPEN_WITHIN_SLA, COALESCE(SUM(p.OPEN_BREACHED_SLA), 0) AS OPEN_BREACHED_SLA FROM ( SELECT c.ITEM_NO, COUNT(*) AS TOTAL_COMPLAINTS, SUM(CASE WHEN c.CLOSE_DT IS NOT NULL AND c.CLOSE_DT <= c.TARGET_COMP_DT THEN 1 ELSE 0 END) AS SOLVED_WITHIN_SLA, SUM(CASE WHEN c.CLOSE_DT IS NULL AND (c.TARGET_COMP_DT IS NULL OR c.TARGET_COMP_DT >= CURDATE()) THEN 1 ELSE 0 END) AS OPEN_WITHIN_SLA, SUM(CASE WHEN c.CLOSE_DT IS NULL AND c.TARGET_COMP_DT < CURDATE() THEN 1 ELSE 0 END) AS OPEN_BREACHED_SLA FROM JAN_SERVICE_CCR_zoho c WHERE c.ORG_ID = @orgId AND DATE(c.CCRDT) >= DATE(@fromDate) AND DATE(c.CCRDT) <= DATE(@toDate) GROUP BY c.ITEM_NO ) p LEFT JOIN ( SELECT ITEM_NO, MAX(WEEK_SALE_QTY) AS ORDERS_DELIVERED FROM JAN_SERVICE_CCR_zoho WHERE ORG_ID = @orgId AND DATE(CCRDT) >= DATE(@fromDate) AND DATE(CCRDT) <= DATE(@toDate) GROUP BY ITEM_NO ) io ON io.ITEM_NO = p.ITEM_NO');

-- ==========================================
-- Seed Initial RBAC Data
-- ==========================================

-- Seed Roles
INSERT INTO JAN_ROLES (ROLE_ID, ROLE_CODE, ROLE_NAME, SOURCE_TYPE, REMARKS, ROLE_VERSION, STATUS, CREATED_BY) VALUES
(1, 'ADM', 'Administrator', 'ADMIN', 'Super admin role with access to everything', '1.0', 'ACTIVE', 'system'),
(2, 'USR', 'Standard User', 'USER', 'Standard corporate employee access role', '1.0', 'ACTIVE', 'system');

-- Seed Modules (using sequential MOD001 - MOD008 codes)
INSERT INTO JAN_MODULES (MODULE_ID, MODULE_CODE, MODULE_NAME, DEFAULT_MENU, SORT_ORDER, REMARKS, STATUS, CREATED_BY) VALUES
(1, 'MOD001', 'Admin',   'Main',             1, 'Admin module',   'ACTIVE', 'SYSTEM'),
(2, 'MOD002', 'PES',     'Dashboards',       2, 'PES module',     'ACTIVE', 'SYSTEM'),
(3, 'MOD003', 'PESLite', 'Branch Planner',   3, 'PESLite module', 'ACTIVE', 'SYSTEM'),
(4, 'MOD004', 'DMS',     'Documents',        4, 'DMS module',     'ACTIVE', 'SYSTEM'),
(5, 'MOD005', 'SCM',     'Procurement',      5, 'SCM module',     'ACTIVE', 'SYSTEM'),
(6, 'MOD006', 'PMS',     'Projects',         6, 'PMS module',     'ACTIVE', 'SYSTEM'),
(7, 'MOD007', 'MES',     'Shop Floor',       7, 'MES module',     'ACTIVE', 'SYSTEM'),
(8, 'MOD008', 'Finance', 'Masters',          8, 'Finance module', 'ACTIVE', 'SYSTEM');

-- Seed Menus (using sequential MNU001 - MNU039 codes)
INSERT INTO JAN_MENUS (MENU_ID, MENU_CODE, MENU_NAME, DISPLAY_NAME, MODULE_ID, PARENT_MENU_ID, MENU_TYPE, NATURE, SORT_ORDER, STATUS, CREATED_BY, MENU_PATH, MENU_ICON) VALUES
-- Admin
(1, 'MNU001', 'Main', 'Main', 1, NULL, 'MASTER', 'PARENT', 1, 'ACTIVE', 'SYSTEM', '/admin/main', 'settings'),
(2, 'MNU002', 'User Master', 'User Master', 1, 1, 'MASTER', 'CHILD', 1, 'ACTIVE', 'SYSTEM', '/admin/user-master', 'user'),
(3, 'MNU003', 'Role Master', 'Role Master', 1, 1, 'MASTER', 'CHILD', 2, 'ACTIVE', 'SYSTEM', '/admin/role-master', 'shield'),
(4, 'MNU004', 'Module Master', 'Module Master', 1, 1, 'MASTER', 'CHILD', 3, 'ACTIVE', 'SYSTEM', '/admin/module-master', 'boxes'),
(5, 'MNU005', 'Menu Master', 'Menu Master', 1, 1, 'MASTER', 'CHILD', 4, 'ACTIVE', 'SYSTEM', '/admin/menu-master', 'menu'),
(6, 'MNU006', 'Role vs Module', 'Role vs Module', 1, 1, 'MASTER', 'CHILD', 5, 'ACTIVE', 'SYSTEM', '/admin/role-vs-module', 'link'),
(7, 'MNU007', 'Role vs Menu', 'Role vs Menu', 1, 1, 'MASTER', 'CHILD', 6, 'ACTIVE', 'SYSTEM', '/admin/role-vs-menu', 'list-checks'),
(8, 'MNU008', 'User Access Rights', 'User Access Rights', 1, 1, 'MASTER', 'CHILD', 7, 'ACTIVE', 'SYSTEM', '/admin/user-access-rights', 'key'),
(9, 'MNU009', 'User Hierarchy', 'User Hierarchy', 1, 1, 'MASTER', 'CHILD', 8, 'ACTIVE', 'SYSTEM', '/admin/user-hierarchy', 'network'),

-- PES
(10, 'MNU010', 'Dashboards', 'Dashboards', 2, NULL, 'REPORT', 'PARENT', 1, 'ACTIVE', 'SYSTEM', '/pes/dashboards', 'layout-dashboard'),
(11, 'MNU011', 'Planning & Execution Control', 'Planning & Execution Control', 2, 10, 'REPORT', 'CHILD', 1, 'ACTIVE', 'SYSTEM', '/pes/dashboards/planning-execution-control', 'activity'),
(12, 'MNU012', 'Operations Dashboard', 'Operations Dashboard', 2, 10, 'REPORT', 'CHILD', 2, 'ACTIVE', 'SYSTEM', '/pes/dashboards/operations-dashboard', 'gauge'),
(13, 'MNU013', 'Planning Overview', 'Planning Overview', 2, 10, 'REPORT', 'CHILD', 3, 'ACTIVE', 'SYSTEM', '/pes/dashboards/planning-overview', 'calendar-days'),
(14, 'MNU014', 'Executive Summary', 'Executive Summary', 2, 10, 'REPORT', 'CHILD', 4, 'ACTIVE', 'SYSTEM', '/pes/dashboards/executive-summary', 'presentation'),
(40, 'MNU040', 'Product Complaint', 'Product Complaint', 2, 10, 'REPORT', 'CHILD', 5, 'ACTIVE', 'SYSTEM', '/pes/dashboards/product-complaint', 'alert-circle'),
(15, 'MNU015', 'KPI\'s', 'KPI\'s', 2, NULL, 'REPORT', 'PARENT', 2, 'ACTIVE', 'SYSTEM', '/pes/kpis', 'chart-no-axes-combined'),
(16, 'MNU016', 'OCQ completion', 'OCQ completion', 2, 15, 'REPORT', 'CHILD', 1, 'ACTIVE', 'SYSTEM', '/pes/kpis/ocq-completion', 'circle-check'),
(17, 'MNU017', 'On-Time Delivery', 'On-Time Delivery', 2, 15, 'REPORT', 'CHILD', 2, 'ACTIVE', 'SYSTEM', '/pes/kpis/on-time-delivery', 'clock'),
(18, 'MNU018', 'Customer Rejection PPM', 'Customer Rejection PPM', 2, 15, 'REPORT', 'CHILD', 3, 'ACTIVE', 'SYSTEM', '/pes/kpis/customer-rejection-ppm', 'alert-triangle'),
(19, 'MNU019', 'Fill Rate', 'Fill Rate', 2, 15, 'REPORT', 'CHILD', 4, 'ACTIVE', 'SYSTEM', '/pes/kpis/fill-rate', 'percent'),
(20, 'MNU020', 'Alerts', 'Alerts', 2, NULL, 'TRANSACTION', 'PARENT', 3, 'ACTIVE', 'SYSTEM', '/pes/alerts', 'bell'),
(21, 'MNU021', 'Active Alerts', 'Active Alerts', 2, 20, 'TRANSACTION', 'CHILD', 1, 'ACTIVE', 'SYSTEM', '/pes/alerts/active-alerts', 'bell-ring'),
(22, 'MNU022', 'Alert History', 'Alert History', 2, 20, 'REPORT', 'CHILD', 2, 'ACTIVE', 'SYSTEM', '/pes/alerts/alert-history', 'history'),
(23, 'MNU023', 'Alert Configuration', 'Alert Configuration', 2, 20, 'MASTER', 'CHILD', 3, 'ACTIVE', 'SYSTEM', '/pes/alerts/alert-configuration', 'sliders-horizontal'),
(24, 'MNU024', 'Transactions', 'Transactions', 2, NULL, 'TRANSACTION', 'PARENT', 4, 'ACTIVE', 'SYSTEM', '/pes/transactions', 'repeat'),
(25, 'MNU025', 'Product Custodian Portfolio', 'Product Custodian Portfolio', 2, 24, 'TRANSACTION', 'CHILD', 1, 'ACTIVE', 'SYSTEM', '/pes/transactions/product-custodian-portfolio', 'briefcase'),
(26, 'MNU026', 'Branch Planner', 'Branch Planner', 2, 24, 'TRANSACTION', 'CHILD', 2, 'ACTIVE', 'SYSTEM', '/pes/transactions/branch-planner', 'map-pinned'),
(27, 'MNU027', 'HO Planner', 'HO Planner', 2, 24, 'TRANSACTION', 'CHILD', 3, 'ACTIVE', 'SYSTEM', '/pes/transactions/ho-planner', 'building-2'),
(28, 'MNU028', 'Demand Forecast', 'Demand Forecast', 2, 24, 'TRANSACTION', 'CHILD', 4, 'ACTIVE', 'SYSTEM', '/pes/transactions/demand-forecast', 'trending-up'),
(29, 'MNU029', 'Replenishment Orders', 'Replenishment Orders', 2, 24, 'TRANSACTION', 'CHILD', 5, 'ACTIVE', 'SYSTEM', '/pes/transactions/replenishment-orders', 'package-plus'),

-- PESLite
(30, 'MNU030', 'Branch Planner', 'Branch Planner', 3, NULL, 'TRANSACTION', 'MENU', 1, 'ACTIVE', 'SYSTEM', '/peslite/branch-planner', 'map-pinned'),
(31, 'MNU031', 'HO Planner', 'HO Planner', 3, NULL, 'TRANSACTION', 'MENU', 2, 'ACTIVE', 'SYSTEM', '/peslite/ho-planner', 'building-2'),
(32, 'MNU032', 'Product Custodian', 'Product Custodian', 3, NULL, 'TRANSACTION', 'MENU', 3, 'ACTIVE', 'SYSTEM', '/peslite/product-custodian', 'briefcase'),
(33, 'MNU033', 'Commodity Custodian', 'Commodity Custodian', 3, NULL, 'TRANSACTION', 'MENU', 4, 'ACTIVE', 'SYSTEM', '/peslite/commodity-custodian', 'boxes'),
(34, 'MNU034', 'Vendor Planner', 'Vendor Planner', 3, NULL, 'TRANSACTION', 'MENU', 5, 'ACTIVE', 'SYSTEM', '/peslite/vendor-planner', 'users'),

-- DMS
(35, 'MNU035', 'Documents', 'Documents', 4, NULL, 'TRANSACTION', 'MENU', 1, 'ACTIVE', 'SYSTEM', '/dms/documents', 'file-text'),

-- SCM
(36, 'MNU036', 'Procurement', 'Procurement', 5, NULL, 'TRANSACTION', 'MENU', 1, 'ACTIVE', 'SYSTEM', '/scm/procurement', 'shopping-cart'),

-- PMS
(37, 'MNU037', 'Projects', 'Projects', 6, NULL, 'TRANSACTION', 'MENU', 1, 'ACTIVE', 'SYSTEM', '/pms/projects', 'folder-kanban'),

-- MES
(38, 'MNU038', 'Shop Floor', 'Shop Floor', 7, NULL, 'TRANSACTION', 'MENU', 1, 'ACTIVE', 'SYSTEM', '/mes/shop-floor', 'factory'),

-- Finance
(39, 'MNU039', 'Masters', 'Masters', 8, NULL, 'MASTER', 'MENU', 1, 'ACTIVE', 'SYSTEM', '/finance/masters', 'dollar-sign');

-- Seed User Master (username: admin, password: password, employeeId: EMP1001)
INSERT INTO JAN_USER_MASTER (USER_ID, USER_CODE, EMPLOYEE_ID, FULL_NAME, USER_NAME, PASSWORD_HASH, PASSWORD_SALT, USER_TYPE, SECURITY_LEVEL, ROLE_ID, VALID_FROM, STATUS, PRIMARY_EMAIL, CREATED_BY) VALUES
(1, 'U0001', 'EMP1001', 'Admin User', 'admin', 'dummysalt_hash', 'dummysalt_salt', 'EMPLOYEE', 5, 1, '2026-08-30', 'ACTIVE', 'admin@company.com', 'system');

-- Seed Role Menu permissions for Admin role (Full permissions on all newly inserted menus)
INSERT INTO JAN_ROLE_MENU (ROLE_ID, MODULE_ID, MENU_ID, PERM_VIEW, PERM_ADD, PERM_EDIT, PERM_DELETE, PERM_EXPORT, PERM_APPROVE, CREATED_BY)
SELECT 1, MODULE_ID, MENU_ID, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'SYSTEM' FROM JAN_MENUS;
